"""add holding_changes holding_daily_pnl and cost_nav

Revision ID: 9c78e7c30ff5
Revises: f24fccd66eba
Create Date: 2026-02-28 10:11:49.387223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c78e7c30ff5'
down_revision: Union[str, None] = 'f24fccd66eba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holding_changes',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('import_id', sa.BigInteger(), nullable=False, comment='关联 import_records.id'),
    sa.Column('holding_id', sa.BigInteger(), nullable=True, comment='关联 fund_holdings.id'),
    sa.Column('fund_code', sa.String(length=10), nullable=False),
    sa.Column('fund_name', sa.String(length=200), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=True),
    sa.Column('change_type', sa.String(length=20), nullable=False, comment='new/increase/decrease/clear'),
    sa.Column('shares_before', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('shares_after', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('shares_delta', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('nav_at_change', sa.Numeric(precision=10, scale=4), nullable=True, comment='变动时净值'),
    sa.Column('mv_before', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('mv_after', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_hc_fund_code', 'holding_changes', ['fund_code'], unique=False)
    op.create_index('idx_hc_import_id', 'holding_changes', ['import_id'], unique=False)
    op.create_table('holding_daily_pnl',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('pnl_date', sa.Date(), nullable=False),
    sa.Column('holding_id', sa.BigInteger(), nullable=False, comment='关联 fund_holdings.id'),
    sa.Column('fund_code', sa.String(length=10), nullable=False),
    sa.Column('shares', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('nav', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('prev_nav', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=16, scale=4), nullable=True, comment='日盈亏额'),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True, comment='日盈亏率%'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('holding_id', 'pnl_date', name='uk_holding_pnl_date')
    )
    op.create_index('idx_pnl_date', 'holding_daily_pnl', ['pnl_date'], unique=False)
    op.create_index('idx_pnl_fund_code', 'holding_daily_pnl', ['fund_code'], unique=False)
    op.add_column('fund_holdings', sa.Column('cost_nav', sa.Numeric(precision=10, scale=4), nullable=True, comment='持仓成本净值(用户可编辑)'))
    # Migrate existing data: set cost_nav from nav_on_import
    op.execute("UPDATE fund_holdings SET cost_nav = nav_on_import WHERE cost_nav IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fund_holdings', 'cost_nav')
    op.drop_index('idx_pnl_fund_code', table_name='holding_daily_pnl')
    op.drop_index('idx_pnl_date', table_name='holding_daily_pnl')
    op.drop_table('holding_daily_pnl')
    op.drop_index('idx_hc_import_id', table_name='holding_changes')
    op.drop_index('idx_hc_fund_code', table_name='holding_changes')
    op.drop_table('holding_changes')
    # ### end Alembic commands ###
