"""initial_tables

Revision ID: f24fccd66eba
Revises: 
Create Date: 2026-02-27 21:45:48.850934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f24fccd66eba'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fund_holdings',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fund_code', sa.String(length=10), nullable=False),
    sa.Column('fund_name', sa.String(length=200), nullable=False),
    sa.Column('share_type', sa.String(length=20), nullable=True),
    sa.Column('management_company', sa.String(length=100), nullable=True),
    sa.Column('platform', sa.String(length=100), nullable=False, comment='销售机构'),
    sa.Column('fund_account', sa.String(length=50), nullable=False, comment='基金账户'),
    sa.Column('trade_account', sa.String(length=50), nullable=False, comment='交易账户'),
    sa.Column('shares', sa.Numeric(precision=16, scale=4), nullable=False, comment='持有份额'),
    sa.Column('share_date', sa.Date(), nullable=False),
    sa.Column('nav_on_import', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('nav_date', sa.Date(), nullable=True),
    sa.Column('market_value', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('dividend_mode', sa.String(length=20), nullable=True),
    sa.Column('last_import_id', sa.BigInteger(), nullable=True),
    sa.Column('status', sa.SmallInteger(), nullable=True, comment='1=持有 0=已清仓'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_code', 'platform', 'fund_account', 'trade_account', name='uk_holding')
    )
    op.create_table('fund_nav_history',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fund_code', sa.String(length=10), nullable=False),
    sa.Column('nav_date', sa.Date(), nullable=False),
    sa.Column('unit_nav', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('acc_nav', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('change_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_code', 'nav_date', name='uk_fund_nav_date')
    )
    op.create_table('funds',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('fund_code', sa.String(length=10), nullable=False, comment='基金代码'),
    sa.Column('fund_name', sa.String(length=200), nullable=False),
    sa.Column('fund_type', sa.String(length=50), nullable=True, comment='基金类型'),
    sa.Column('management_company', sa.String(length=100), nullable=True),
    sa.Column('latest_nav', sa.Numeric(precision=10, scale=4), nullable=True, comment='最新净值（缓存）'),
    sa.Column('latest_nav_date', sa.Date(), nullable=True),
    sa.Column('nav_change_pct', sa.Numeric(precision=8, scale=4), nullable=True, comment='最新涨跌幅%'),
    sa.Column('status', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('fund_code')
    )
    op.create_table('import_records',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='防重复导入'),
    sa.Column('total_rows', sa.Integer(), nullable=True),
    sa.Column('new_holdings', sa.Integer(), nullable=True),
    sa.Column('updated_holdings', sa.Integer(), nullable=True),
    sa.Column('removed_holdings', sa.Integer(), nullable=True),
    sa.Column('error_rows', sa.Integer(), nullable=True),
    sa.Column('data_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('total_market_value', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('total_shares_count', sa.Integer(), nullable=False),
    sa.Column('daily_pnl', sa.Numeric(precision=16, scale=4), nullable=True),
    sa.Column('daily_pnl_pct', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('platform_breakdown', sa.JSON(), nullable=True, comment='按平台市值分布'),
    sa.Column('holdings_detail', sa.JSON(), nullable=True, comment='全量持仓明细快照'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('snapshot_date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('portfolio_snapshots')
    op.drop_table('import_records')
    op.drop_table('funds')
    op.drop_table('fund_nav_history')
    op.drop_table('fund_holdings')
    # ### end Alembic commands ###
